name: 'Continuous Integration'
on:
  workflow_dispatch:
  push:
    branches:
      - 'feature/**'
      - 'fix/**'
  pull_request:
    branches:
      - 'feature/**'
      - 'fix/**'
jobs:
  build:
    name: 'Build 🏗'
    strategy:
      matrix:
        os:
          - ubuntu-latest
        python-version:
          - '3.11'
    defaults:
      run:
        working-directory: app/
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check repository
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
  code-quality:
    name: 'Code-Quality 💎'
    needs: build
    strategy:
      matrix:
        os:
          - ubuntu-latest
        python-version:
          - '3.11'
    defaults:
      run:
        working-directory: app/
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check repository
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install dev dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Install Dependencies for Linting
        run: |
          pip install flake8
      - name: Lint with Black
        uses: psf/black@stable
        with:
          options: '--exclude=tests/'
          src: 'app/src/'
      - name: Lint with Isort
        run: |
          isort . --profile black
      - name: Lint with MyPy
        run: |
          mypy . --pretty

  test:
    name: 'Test 🔬'
    needs: build
    strategy:
      matrix:
        os:
          - ubuntu-latest
        python-version:
          - '3.11'
    defaults:
      run:
        working-directory: app/
    env:
      ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
      DEBUG: ${{ secrets.DEBUG }}
      API_VERSION: ${{ secrets.API_VERSION }}
      BACKEND_SERVER_HOST: ${{ secrets.BACKEND_SERVER_HOST }}
      BACKEND_SERVER_PORT: ${{ secrets.BACKEND_SERVER_PORT }}
      BACKEND_SERVER_WORKERS: ${{ secrets.BACKEND_SERVER_WORKERS }}
      STATIC_DIR_NAME: ${{ secrets.STATIC_DIR_NAME }}
      APP_DIR_NAME: ${{ secrets.APP_DIR_NAME }}
      ML_MODEL_DIR_NAME: ${{ secrets.ML_MODEL_DIR_NAME }}
      ML_PYTORCH_MODEL: ${{ secrets.ML_PYTORCH_MODEL }}
      ML_LOCAL_MODEL_FILENAME: ${{ secrets.ML_LOCAL_MODEL_FILENAME }}
      IS_ALLOWED_CREDENTIALS: ${{ secrets.IS_ALLOWED_CREDENTIALS }}
      ALLOWED_ALL_ORIGINS: ${{ secrets.ALLOWED_ALL_ORIGINS }}
      ALLOWED_ALL_HEADERS: ${{ secrets.ALLOWED_ALL_HEADERS }}
      ALLOWED_ALL_METHODS: ${{ secrets.ALLOWED_ALL_METHODS }}
      API_TOKEN: ${{ secrets.API_TOKEN }}
      AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
      ML_MODEL_VERSION: ${{ secrets.ML_MODEL_VERSION }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check repository
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Install Dependencies for Testing
        run: |
          pip install pytest pytest-asyncio pytest-cov pytest-xdist
      - name: Test with Pytest-Cov
        run: |
          pytest --cov --cov-report xml .
